# Generated by Django 6.0.3 on 2026-05-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subscription_contact_email_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
