# Generated by Django 6.0.3 on 2026-05-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subscription_deposit_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='tenant_count',
        ),
    ]
