# Generated by Django 6.0.3 on 2026-05-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_subscription_tenant_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='room_name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor_number',
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_name']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-start_date', 'room__room_name']},
        ),
        migrations.AlterModelOptions(
            name='usage',
            options={'ordering': ['-period', 'subscription__room__room_name']},
        ),
    ]
