# Generated by Django 6.0.3 on 2026-05-29 19:05

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_room_number_remove_floor_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(
                condition=Q(status='enabled'),
                fields=('room',),
                name='unique_enabled_subscription_per_room',
            ),
        ),
    ]
