# Generated by Django 6.0.3 on 2026-05-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_unique_enabled_subscription_per_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='start_electricity_reading',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_water_reading',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
