# Generated by Django 6.0.3 on 2026-05-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_subscription_start_readings'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='contact_phonenumber',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
