# Generated by Django 6.0.3 on 2026-05-29 20:20

import django.db.models.deletion
from django.db import migrations, models


def move_vehicle_room_to_subscription(apps, schema_editor):
    Vehicle = apps.get_model('main', 'Vehicle')
    Subscription = apps.get_model('main', 'Subscription')

    for vehicle in Vehicle.objects.select_related('room').all():
        subscription = (
            Subscription.objects.filter(room=vehicle.room, status='enabled')
            .order_by('-start_date', '-id')
            .first()
        )
        if subscription is None:
            subscription = (
                Subscription.objects.filter(room=vehicle.room)
                .order_by('-start_date', '-id')
                .first()
            )
        if subscription is None:
            raise RuntimeError(
                f'Cannot migrate vehicle {vehicle.license_plate}: room {vehicle.room_id} has no matching subscription.'
            )
        vehicle.subscription_id = subscription.id
        vehicle.save(update_fields=['subscription'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='main.subscription'),
        ),
        migrations.RunPython(move_vehicle_room_to_subscription, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='vehicle',
            name='room',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='main.subscription'),
        ),
    ]
