# Generated by Django 6.0.3 on 2026-05-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_vehicle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetemplate',
            name='laundry_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
