# Generated by Django 6.0.3 on 2026-05-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_pricetemplate_laundry_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='laundry_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='usage',
            name='laundry_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
