# Generated by Django 6.0.3 on 2026-08-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_subscription_optional_internet_laundry'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
    ]
